// packages/remix-router/src/ScriptOnce.tsx
/** @jsxRuntime automatic */
/** @jsxImportSource @remix-run/ui */
import { useRouter } from './useRouter'
import type { Handle, RemixNode } from '@remix-run/ui'

const isServer = typeof document === 'undefined'

export interface ScriptOnceProps {
  children: string
}

/**
 * Server-only helper: emits an inline `<script>` exactly once during SSR
 * and removes itself on client load. No-op on the client.
 */
export function ScriptOnce(handle: Handle<ScriptOnceProps>) {
  const router = useRouter(handle)
  return ({ children }: ScriptOnceProps): RemixNode => {
    if (!isServer && !router.isServer) return null
    const nonce = router.options.ssr?.nonce
    return (
      <script
        nonce={nonce}
        innerHTML={children + ';document.currentScript.remove()'}
      />
    )
  }
}

// packages/vue-router/src/ScriptOnce.tsx
import * as Vue from 'vue'
import { useRouter } from './useRouter'

export const ScriptOnce = Vue.defineComponent({
  name: 'ScriptOnce',
  props: {
    children: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const router = useRouter()

    if (router.isServer) {
      return () => (
        <script
          nonce={router.options.ssr?.nonce}
          innerHTML={props.children + ';document.currentScript.remove()'}
        />
      )
    }

    const mounted = Vue.ref(false)
    Vue.onMounted(() => {
      mounted.value = true
    })

    return () => {
      if (mounted.value) {
        return null
      }

      return (
        <script
          nonce={router.options.ssr?.nonce}
          data-allow-mismatch
          innerHTML=""
        />
      )
    }
  },
})
