// examples/angular/basic-file-based/src/routes/anchor.ts
import { Component } from '@angular/core'
import { createFileRoute, Link } from '@tanstack/angular-router-experimental'

export const Route = createFileRoute('/anchor')({
  component: () => AnchorComponent,
})

@Component({
  selector: 'route-component',
  standalone: true,
  template: `
    <div class="flex flex-col w-full">
      <nav class="sticky top-0 z-10 p-2 bg-gray-50 dark:bg-gray-900 border-b">
        <ul class="inline-flex gap-2">
          <li>
            <a [link]="{
              from: route.fullPath,
              hash: 'default-anchor',
              activeOptions: { includeHash: true },
              activeProps: { class: 'font-bold active' }
            }">Default Anchor</a>
          </li>
          <li>
            <a [link]="{
              from: route.fullPath,
              hash: 'false-anchor',
              hashScrollIntoView: false,
              activeOptions: { includeHash: true },
              activeProps: { class: 'font-bold active' }
            }">No Scroll Into View</a>
          </li>
          <li>
            <a [link]="{
              from: route.fullPath,
              hash: 'smooth-scroll',
              hashScrollIntoView: { behavior: 'smooth' },
              activeOptions: { includeHash: true },
              activeProps: { class: 'font-bold active' }
            }">Smooth Scroll</a>
          </li>
        </ul>
      </nav>
      <main class="overflow-auto">
        <div id="default-anchor" class="p-2 min-h-dvh">
          <h1 class="font-bold text-xl pt-10">Default Anchor</h1>
        </div>
        <div id="false-anchor" class="p-2 min-h-dvh">
          <h1 class="font-bold text-xl pt-10">No Scroll Into View</h1>
        </div>
        <div id="smooth-scroll" class="p-2 min-h-dvh">
          <h1 class="font-bold text-xl pt-10">Smooth Scroll</h1>
        </div>
      </main>
    </div>
  `,
  imports: [Link],
})
class AnchorComponent {
  route = Route
}

// examples/preact/basic-file-based/src/routes/anchor.tsx
import { createFileRoute } from '@tanstack/preact-router'
import { useLayoutEffect, useRef, useState } from 'preact/hooks'
import { Link, useLocation, useNavigate } from '@tanstack/preact-router'

export const Route = createFileRoute('/anchor')({
  component: AnchorComponent,
})

const anchors: Array<{
  id: string
  title: string
  hashScrollIntoView?: boolean | ScrollIntoViewOptions
}> = [
  {
    id: 'default-anchor',
    title: 'Default Anchor',
  },
  {
    id: 'false-anchor',
    title: 'No Scroll Into View',
    hashScrollIntoView: false,
  },
  {
    id: 'smooth-scroll',
    title: 'Smooth Scroll',
    hashScrollIntoView: { behavior: 'smooth' },
  },
] as const

function AnchorSection({ id, title }: { id: string; title: string }) {
  const [hasShown, setHasShown] = useState(false)
  const elementRef = useRef<HTMLHeadingElement>(null)

  useLayoutEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (!hasShown && entry.isIntersecting) {
          setHasShown(true)
        }
      },
      { threshold: 0.01 },
    )

    const currentRef = elementRef.current
    if (currentRef) {
      observer.observe(currentRef)
    }

    return () => {
      if (currentRef) {
        observer.unobserve(currentRef)
      }
    }
  }, [hasShown])

  return (
    <div id={id} className="p-2 min-h-dvh">
      <h1 className="font-bold text-xl pt-10" ref={elementRef}>
        {title}
        {hasShown ? ' (shown)' : ''}
      </h1>
    </div>
  )
}

function AnchorComponent() {
  const navigate = useNavigate()
  const location = useLocation()
  const [withScroll, setWithScroll] = useState(true)

  return (
    <div className="flex flex-col w-full">
      <nav className="sticky top-0 z-10 p-2 bg-gray-50 dark:bg-gray-900 border-b">
        <ul className="inline-flex gap-2">
          {anchors.map((anchor) => (
            <li key={anchor.id}>
              <Link
                from={Route.fullPath}
                hash={anchor.id}
                activeOptions={{ includeHash: true }}
                activeProps={{
                  className: 'font-bold active',
                }}
                hashScrollIntoView={anchor.hashScrollIntoView}
              >
                {anchor.title}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
      <main className="overflow-auto">
        <form
          className="p-2 space-y-2 min-h-dvh"
          onSubmit={(event) => {
            event.preventDefault()
            event.stopPropagation()
            const formData = new FormData(event.target as HTMLFormElement)

            const toHash = formData.get('hash') as string

            if (!toHash) {
              return
            }

            const hashScrollIntoView = withScroll
              ? ({
                  behavior: formData.get('scrollBehavior') as ScrollBehavior,
                  block: formData.get('scrollBlock') as ScrollLogicalPosition,
                  inline: formData.get('scrollInline') as ScrollLogicalPosition,
                } satisfies ScrollIntoViewOptions)
              : false

            navigate({ hash: toHash, hashScrollIntoView })
          }}
        >
          <h1 className="font-bold text-xl">Scroll with navigate</h1>
          <div className="space-y-2">
            <label>
              <span>Target Anchor</span>
              <select
                className="border border-opacity-50 rounded p-2 w-full"
                defaultValue={location.hash || anchors[0].id}
                name="hash"
              >
                {anchors.map((anchor) => (
                  <option key={anchor.id} value={anchor.id}>
                    {anchor.title}
                  </option>
                ))}
              </select>
            </label>
            <div>
              <label>
                <input
                  checked={withScroll}
                  onChange={(e) => setWithScroll((e.target as HTMLInputElement).checked)}
                  type="checkbox"
                />{' '}
                Scroll Into View
              </label>
            </div>
          </div>
          {withScroll ? (
            <>
              <div className="space-y-2">
                <label>
                  <span>Behavior</span>
                  <select
                    className="border border-opacity-50 rounded p-2 w-full"
                    defaultValue="instant"
                    name="scrollBehavior"
                  >
                    <option value="instant">instant</option>
                    <option value="smooth">smooth</option>
                    <option value="auto">auto</option>
                  </select>
                </label>
              </div>

              <div className="space-y-2">
                <label>
                  <span>Block</span>
                  <select
                    className="border border-opacity-50 rounded p-2 w-full"
                    defaultValue="start"
                    name="scrollBlock"
                  >
                    <option value="start">start</option>
                    <option value="center">center</option>
                    <option value="end">end</option>
                    <option value="nearest">nearest</option>
                  </select>
                </label>
              </div>

              <div className="space-y-2">
                <label>
                  <span>Inline</span>
                  <select
                    className="border border-opacity-50 rounded p-2 w-full"
                    defaultValue="nearest"
                    name="scrollInline"
                  >
                    <option value="start">start</option>
                    <option value="center">center</option>
                    <option value="end">end</option>
                    <option value="nearest">nearest</option>
                  </select>
                </label>
              </div>
            </>
          ) : null}
          <div>
            <button className="bg-blue-500 rounded p-2 uppercase text-white font-black disabled:opacity-50">
              Navigate
            </button>
          </div>
        </form>

        {anchors.map((anchor) => (
          <AnchorSection key={anchor.id} id={anchor.id} title={anchor.title} />
        ))}
      </main>
    </div>
  )
}
