// benchmarks/client-nav/scenarios/interrupted-navigations/react/src/routes/interrupt.tsx
import { Outlet, createRoute, useRouterState } from '@tanstack/react-router'
import {
  interruptedNavigationHomePath,
  interruptedNavigationRoutePaths,
  interruptedNavigationScenarioSlug,
} from '../../../shared.ts'
import { rootRoute } from './__root'

export const interruptRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: interruptedNavigationRoutePaths.home,
  component: InterruptLayout,
})

function InterruptLayout() {
  const pathname = useRouterState({
    select: (state) => state.location.pathname,
  })

  return (
    <>
      <div data-client-nav-scenario={interruptedNavigationScenarioSlug} />
      {pathname === interruptedNavigationHomePath ? (
        <main data-interrupted-page="home" />
      ) : null}
      <Outlet />
    </>
  )
}

// benchmarks/client-nav/scenarios/interrupted-navigations/vue/src/routes/interrupt.tsx
import * as Vue from 'vue'
import { Outlet, createRoute, useRouterState } from '@tanstack/vue-router'
import {
  interruptedNavigationHomePath,
  interruptedNavigationRoutePaths,
  interruptedNavigationScenarioSlug,
} from '../../../shared.ts'
import { rootRoute } from './__root'

const InterruptLayout: ReturnType<typeof Vue.defineComponent> =
  Vue.defineComponent({
    setup() {
      const pathname = useRouterState({
        select: (state) => state.location.pathname,
      })

      return () => (
        <>
          <div data-client-nav-scenario={interruptedNavigationScenarioSlug} />
          {pathname.value === interruptedNavigationHomePath ? (
            <main data-interrupted-page="home" />
          ) : null}
          <Outlet />
        </>
      )
    },
  })

export const interruptRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: interruptedNavigationRoutePaths.home,
  component: InterruptLayout,
})
