// benchmarks/ssr/scenarios/loaders/vue/src/routes/$a.$b.tsx
import { defineComponent } from 'vue'
import { Outlet, createFileRoute } from '@tanstack/vue-router'
import { makeLevelData } from '../../../shared-data'

const LevelBComponent = defineComponent({
  setup() {
    const data = Route.useLoaderData()

    return () => (
      <section>
        <h2>{data.value.meta.label}</h2>
        <ul>
          {data.value.items.slice(0, 10).map((item) => (
            <li key={item.id}>{item.name}</li>
          ))}
        </ul>
        <Outlet />
      </section>
    )
  },
})

export const Route = createFileRoute('/$a/$b')({
  beforeLoad: ({ params, context }) => {
    void context

    return { ctxB: `v-${params.b}` }
  },
  loaderDeps: ({ search }) => ({ page: search.page }),
  loader: async ({ params, deps, context }) => {
    void context

    return makeLevelData(params.b, deps.page)
  },
  component: LevelBComponent,
})

// benchmarks/ssr/scenarios/before-load/react/src/routes/$a.$b.tsx
import { Outlet, createFileRoute } from '@tanstack/react-router'
import type { BeforeLoadContext } from '../../../shared'

export const Route = createFileRoute('/$a/$b')({
  beforeLoad: ({ params, context }) => {
    const parent = context as BeforeLoadContext

    return {
      chainToken: `${parent.chainToken}.${params.b}`,
      ctxB: params.b,
    }
  },
  component: LevelBComponent,
})

function LevelBComponent() {
  return <Outlet />
}
