// benchmarks/memory/server/scenarios/peak-large-page/solid/src/routes/l1.l2.l3.l4.tsx
import { Outlet, createFileRoute } from '@tanstack/solid-router'
import {
  makeLargePageHead,
  makeLargePageLevelData,
} from '../../../large-page-data'

export const Route = createFileRoute('/l1/l2/l3/l4')({
  loader: () => makeLargePageLevelData(4, 0x5eed_1004),
  head: ({ loaderData }) => makeLargePageHead(loaderData),
  component: LevelFourComponent,
})

function LevelFourComponent() {
  const data = Route.useLoaderData()
  const first = () => data().records[0]!

  return (
    <section data-bench={data().marker}>
      <h2>{data().marker}</h2>
      <p>records: {data().records.length}</p>
      <article>
        <h3>{first().name}</h3>
        <p>{first().id}</p>
        <p>{first().description}</p>
      </article>
      <Outlet />
    </section>
  )
}

// benchmarks/memory/server/scenarios/peak-large-page/vue/src/routes/l1.l2.l3.l4.tsx
import { defineComponent } from 'vue'
import { Outlet, createFileRoute } from '@tanstack/vue-router'
import {
  makeLargePageHead,
  makeLargePageLevelData,
} from '../../../large-page-data'

const LevelFourComponent = defineComponent({
  setup() {
    const data = Route.useLoaderData()

    return () => {
      const first = data.value.records[0]!

      return (
        <section data-bench={data.value.marker}>
          <h2>{data.value.marker}</h2>
          <p>records: {data.value.records.length}</p>
          <article>
            <h3>{first.name}</h3>
            <p>{first.id}</p>
            <p>{first.description}</p>
          </article>
          <Outlet />
        </section>
      )
    }
  },
})

export const Route = createFileRoute('/l1/l2/l3/l4')({
  loader: () => makeLargePageLevelData(4, 0x5eed_1004),
  head: ({ loaderData }) => makeLargePageHead(loaderData),
  component: LevelFourComponent,
})
