// benchmarks/memory/server/scenarios/serialization-payload/react/src/routes/data.$id.tsx
import { createFileRoute } from '@tanstack/react-router'
import { makeSerializationPayload } from '../../../serialization-payload'

export const Route = createFileRoute('/data/$id')({
  loader: ({ params }) => makeSerializationPayload(params.id),
  component: DataComponent,
})

function DataComponent() {
  const data = Route.useLoaderData()

  return (
    <main data-bench="serialization-payload">Map size: {data.lookup.size}</main>
  )
}

// benchmarks/memory/server/scenarios/serialization-payload/vue/src/routes/data.$id.tsx
import { defineComponent } from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import { makeSerializationPayload } from '../../../serialization-payload'

const DataComponent = defineComponent({
  setup() {
    const data = Route.useLoaderData()

    return () => (
      <main data-bench="serialization-payload">
        Map size: {data.value.lookup.size}
      </main>
    )
  },
})

export const Route = createFileRoute('/data/$id')({
  loader: ({ params }) => makeSerializationPayload(params.id),
  component: DataComponent,
})
