// examples/solid/kitchen-sink-file-based/src/routes/_auth.profile.tsx
import * as Solid from 'solid-js'


export const Route = createFileRoute({
  component: ProfileComponent,
})

function ProfileComponent() {
  const context = Route.useRouteContext()

  return (
    <div class="p-2 space-y-2">
      <div>
        Username:<strong>{context().username}</strong>
      </div>
    </div>
  )
}

// examples/react/kitchen-sink-react-query-file-based/src/routes/_auth.profile.tsx
import * as React from 'react'


export const Route = createFileRoute({
  component: ProfileComponent,
})

function ProfileComponent() {
  const { username } = Route.useRouteContext()

  return (
    <div className="p-2 space-y-2">
      <div>
        Username:<strong>{username}</strong>
      </div>
    </div>
  )
}
