// examples/react/kitchen-sink-file-based/src/routes/_pathlessLayout.tsx
import * as React from 'react'
import { Outlet, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_pathlessLayout')({
  component: PathlessLayoutComponent,
})

function PathlessLayoutComponent() {
  return (
    <div>
      <div>Pathless Layout</div>
      <hr />
      <Outlet />
    </div>
  )
}

// examples/angular/basic-file-based/src/routes/_pathlessLayout.ts
import { Component } from '@angular/core'
import { createFileRoute, Outlet } from '@tanstack/angular-router-experimental'

export const Route = createFileRoute('/_pathlessLayout')({
  component: () => PathlessLayoutComponent,
})

@Component({
  selector: 'route-component',
  standalone: true,
  template: `
    <div class="p-2">
      <div class="border-b">I'm a pathless layout</div>
      <div><outlet /></div>
    </div>
  `,
  imports: [Outlet],
})
class PathlessLayoutComponent {}
