// benchmarks/client-nav/scenarios/control-flow/vue/src/routes/missing.$id.tsx
import * as Vue from 'vue'
import { createFileRoute, notFound } from '@tanstack/vue-router'

const MissingPage = Vue.defineComponent({
  setup() {
    const data = Route.useLoaderData()
    return () => <div data-testid="missing-state">{data.value.id}</div>
  },
})

const MissingNotFound = Vue.defineComponent({
  setup() {
    return () => <div data-testid="not-found-state">missing not found</div>
  },
})

export const Route = createFileRoute('/missing/$id')({
  staleTime: 0,
  gcTime: 0,
  loader: ({ params }) => {
    if (params.id === 'gone') {
      throw notFound()
    }
    return { id: params.id }
  },
  component: MissingPage,
  notFoundComponent: MissingNotFound,
})

// benchmarks/memory/server/scenarios/error-paths/react/src/routes/missing.$id.tsx
import { createFileRoute, notFound } from '@tanstack/react-router'

export const Route = createFileRoute('/missing/$id')({
  loader: () => {
    throw notFound()
  },
  notFoundComponent: MissingNotFoundComponent,
  component: MissingComponent,
})

function MissingNotFoundComponent() {
  return (
    <main data-bench="not-found-boundary">error-paths-not-found-boundary</main>
  )
}

function MissingComponent() {
  return null
}
