// examples/solid/search-validator-adapters/src/routes/users/arktype.index.tsx
import { useNavigate } from '@tanstack/solid-router'
import { type } from 'arktype'
import { Suspense } from 'solid-js'
import { Header } from '../../components/Header'
import { Users, usersQueryOptions } from '../../components/Users'
import { Content } from '../../components/Content'
import { Search } from '../../components/Search'

const ArkType = () => {
  const search = Route.useSearch({
    select: (search) => search.search,
  })
  const navigate = useNavigate({ from: Route.fullPath })

  return (
    <>
      <Header title="ArkType" />
      <Content>
        <Search
          search={search()}
          onChange={(search) => navigate({ search: { search }, replace: true })}
        />
        <Suspense>
          <Users search={search()} />
        </Suspense>
      </Content>
    </>
  )
}

const search = type({
  search: 'string = ""',
})

export const Route = createFileRoute({
  validateSearch: search,
  loaderDeps: (opt) => ({ search: opt.search }),
  loader: (opt) => {
    opt.context.queryClient.ensureQueryData(
      usersQueryOptions(opt.deps.search.search),
    )
  },
  component: ArkType,
})

// examples/react/search-validator-adapters/src/routes/users/arktype.index.tsx
import * as React from 'react'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { type } from 'arktype'
import { Header } from '../../components/Header'
import { Users, usersQueryOptions } from '../../components/Users'
import { Content } from '../../components/Content'
import { Search } from '../../components/Search'

const ArkType = () => {
  const search = Route.useSearch({
    select: (search) => search.search,
  })
  const navigate = useNavigate({ from: Route.fullPath })

  return (
    <>
      <Header title="ArkType" />
      <Content>
        <Search
          search={search}
          onChange={(search) => navigate({ search: { search }, replace: true })}
        />
        <React.Suspense>
          <Users search={search} />
        </React.Suspense>
      </Content>
    </>
  )
}

const search = type({
  search: 'string = ""',
})

export const Route = createFileRoute('/users/arktype/')({
  validateSearch: search,
  loaderDeps: (opt) => ({ search: opt.search }),
  loader: (opt) => {
    opt.context.queryClient.ensureQueryData(
      usersQueryOptions(opt.deps.search.search),
    )
  },
  component: ArkType,
})
