// benchmarks/ssr/scenarios/global-middleware/solid/src/routes/page.$id.tsx
import { createFileRoute } from '@tanstack/solid-router'
import {
  getGlobalMiddlewareContext,
  makeDocumentMarker,
  type GlobalMiddlewareContext,
} from '../../../shared'

export const Route = createFileRoute('/page/$id')({
  beforeLoad: ({ serverContext }) => ({
    globalMiddlewareContext: (serverContext ?? {}) as GlobalMiddlewareContext,
  }),
  loader: ({ params, context }) => ({
    marker: makeDocumentMarker(params.id, getGlobalMiddlewareContext(context)),
  }),
  component: PageComponent,
})

function PageComponent() {
  const data = Route.useLoaderData()

  return <main>{data().marker}</main>
}

// benchmarks/ssr/scenarios/global-middleware/vue/src/routes/page.$id.tsx
import { defineComponent } from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import {
  getGlobalMiddlewareContext,
  makeDocumentMarker,
  type GlobalMiddlewareContext,
} from '../../../shared'

const PageComponent = defineComponent({
  setup() {
    const data = Route.useLoaderData()

    return () => <main>{data.value.marker}</main>
  },
})

export const Route = createFileRoute('/page/$id')({
  beforeLoad: ({ serverContext }) => ({
    globalMiddlewareContext: (serverContext ?? {}) as GlobalMiddlewareContext,
  }),
  loader: ({ params, context }) => ({
    marker: makeDocumentMarker(params.id, getGlobalMiddlewareContext(context)),
  }),
  component: PageComponent,
})
