// benchmarks/client-nav/scenarios/location-building-links/solid/src/routes/dashboard.projects.$projectId.tasks.$taskId.tsx
import { createFileRoute } from '@tanstack/solid-router'

export const Route = createFileRoute(
  '/dashboard/projects/$projectId/tasks/$taskId',
)({
  component: TaskPage,
})

function TaskPage() {
  const params = Route.useParams()

  return (
    <div
      data-route-marker="task"
      data-project-id={params().projectId}
      data-task-id={params().taskId}
    />
  )
}

// benchmarks/client-nav/scenarios/location-building-links/vue/src/routes/dashboard.projects.$projectId.tasks.$taskId.tsx
import * as Vue from 'vue'
import { createFileRoute } from '@tanstack/vue-router'

const TaskPage = Vue.defineComponent({
  setup() {
    const params = Route.useParams()

    return () => (
      <div
        data-route-marker="task"
        data-project-id={params.value.projectId}
        data-task-id={params.value.taskId}
      />
    )
  },
})

export const Route = createFileRoute(
  '/dashboard/projects/$projectId/tasks/$taskId',
)({
  component: TaskPage,
})
