// packages/vue-router-devtools/src/index.tsx
import { defineComponent } from 'vue'
import * as Devtools from './TanStackRouterDevtools'
import * as DevtoolsPanel from './TanStackRouterDevtoolsPanel'

// Re-export types
export type { TanStackRouterDevtoolsOptions } from './TanStackRouterDevtools'
export type { TanStackRouterDevtoolsPanelOptions } from './TanStackRouterDevtoolsPanel'

// Create a null component for production
const NullComponent = /* #__PURE__ */ defineComponent({
  name: 'NullTanStackRouterDevtools',
  setup(): () => null {
    return () => null
  },
})

export const TanStackRouterDevtools: (typeof Devtools)['TanStackRouterDevtools'] =
  process.env.NODE_ENV !== 'development'
    ? (NullComponent as (typeof Devtools)['TanStackRouterDevtools'])
    : Devtools.TanStackRouterDevtools

export const TanStackRouterDevtoolsInProd: (typeof Devtools)['TanStackRouterDevtools'] =
  Devtools.TanStackRouterDevtools

export const TanStackRouterDevtoolsPanel: (typeof DevtoolsPanel)['TanStackRouterDevtoolsPanel'] =
  process.env.NODE_ENV !== 'development'
    ? (NullComponent as (typeof DevtoolsPanel)['TanStackRouterDevtoolsPanel'])
    : DevtoolsPanel.TanStackRouterDevtoolsPanel

export const TanStackRouterDevtoolsPanelInProd: (typeof DevtoolsPanel)['TanStackRouterDevtoolsPanel'] =
  DevtoolsPanel.TanStackRouterDevtoolsPanel

// packages/angular-router-devtools/src/index.ts
import * as Devtools from './tanstack-router-devtools'
import * as DevtoolsPanel from './tanstack-router-devtools-panel'
import { Component } from '@angular/core'

// No-op component for production
@Component({
  selector: 'router-devtools',
  template: '',
  standalone: true,
})
class NoOpTanStackRouterDevtools {}

@Component({
  selector: 'router-devtools-panel',
  template: '',
  standalone: true,
})
class NoOpTanStackRouterDevtoolsPanel {}

export const TanStackRouterDevtools: typeof Devtools.TanStackRouterDevtools =
  process.env.NODE_ENV !== 'development'
    ? (NoOpTanStackRouterDevtools as any)
    : Devtools.TanStackRouterDevtools

export const TanStackRouterDevtoolsInProd: typeof Devtools.TanStackRouterDevtools =
  Devtools.TanStackRouterDevtools

export const TanStackRouterDevtoolsPanel: typeof DevtoolsPanel.TanStackRouterDevtoolsPanel =
  process.env.NODE_ENV !== 'development'
    ? (NoOpTanStackRouterDevtoolsPanel as any)
    : DevtoolsPanel.TanStackRouterDevtoolsPanel

export const TanStackRouterDevtoolsPanelInProd: typeof DevtoolsPanel.TanStackRouterDevtoolsPanel =
  DevtoolsPanel.TanStackRouterDevtoolsPanel

export type { TanStackRouterDevtoolsOptions } from './tanstack-router-devtools'
export type { TanStackRouterDevtoolsPanelOptions } from './tanstack-router-devtools-panel'
