// examples/react/start-supabase-basic/src/routes/_authed/posts.$postId.tsx
import { ErrorComponent } from '@tanstack/react-router'
import type { ErrorComponentProps } from '@tanstack/react-router'
import { NotFound } from '~/components/NotFound'
import { fetchPost } from '~/utils/posts'

export const Route = createFileRoute({
  loader: ({ params: { postId } }) => fetchPost({ data: postId }),
  errorComponent: PostErrorComponent,
  component: PostComponent,
  notFoundComponent: () => {
    return <NotFound>Post not found</NotFound>
  },
})

export function PostErrorComponent({ error }: ErrorComponentProps) {
  return <ErrorComponent error={error} />
}

function PostComponent() {
  const post = Route.useLoaderData()

  return (
    <div className="space-y-2">
      <h4 className="text-xl font-bold underline">{post.title}</h4>
      <div className="text-sm">{post.body}</div>
    </div>
  )
}

// examples/vue/basic-file-based-jsx/src/routes/posts.$postId.tsx
import { createFileRoute } from '@tanstack/vue-router'
import { defineComponent } from 'vue'
import PostErrorComponent from '../components/PostErrorComponent.vue'
import { fetchPost } from '../posts'
import type { PostType } from '../posts'

const PostComponent = defineComponent({
  setup() {
    const post = Route.useLoaderData()

    return () => (
      <div class="space-y-2">
        <h4 class="text-xl font-bold underline" data-testid="post-title">
          {(post.value as PostType).title}
        </h4>
        <div class="text-sm">{(post.value as PostType).body}</div>
      </div>
    )
  },
})

export const Route = createFileRoute('/posts/$postId')({
  loader: async ({ params: { postId } }) => fetchPost(postId),
  component: PostComponent,
  errorComponent: PostErrorComponent,
  notFoundComponent: () => <p>Post not found</p>,
})
