// examples/react/start-basic-react-query/src/routes/_pathlessLayout/_nested-layout.tsx
import { Link, Outlet, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_pathlessLayout/_nested-layout')({
  component: PathlessLayoutComponent,
})

function PathlessLayoutComponent() {
  return (
    <div>
      <div>I'm a nested pathless layout</div>
      <div className="flex gap-2">
        <Link
          to="/route-a"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Go to route A
        </Link>
        <Link
          to="/route-b"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Go to route B
        </Link>
      </div>
      <div>
        <Outlet />
      </div>
    </div>
  )
}

// examples/angular/basic-file-based/src/routes/_pathlessLayout/_nested-layout.ts
import { Component } from '@angular/core'
import { createFileRoute, Link, Outlet } from '@tanstack/angular-router-experimental'

export const Route = createFileRoute('/_pathlessLayout/_nested-layout')({
  component: () => NestedLayoutComponent,
})

@Component({
  selector: 'route-component',
  standalone: true,
  template: `
    <div>
      <div>I'm a nested pathless layout</div>
      <div class="flex gap-2 border-b">
        <a [link]="{ to: '/route-a', activeProps: { class: 'font-bold' } }">Go to route A</a>
        <a [link]="{ to: '/route-b', activeProps: { class: 'font-bold' } }">Go to route B</a>
      </div>
      <div><outlet /></div>
    </div>
  `,
  imports: [Link, Outlet],
})
class NestedLayoutComponent {}
