// packages/vue-start-client/src/StartClient.tsx
import * as Vue from 'vue'
import { RouterProvider } from '@tanstack/vue-router'
import type { AnyRouter } from '@tanstack/router-core'

export const StartClient = Vue.defineComponent({
  name: 'StartClient',
  props: {
    router: {
      type: Object as () => AnyRouter,
      required: true,
    },
  },
  setup(props) {
    return () => Vue.h(RouterProvider, { router: props.router })
  },
})

// packages/react-router-server/src/client/StartClient.tsx
import { RouterProvider } from '@tanstack/react-router'
import * as React from 'react'
import type { AnyRouter } from '@tanstack/react-router'

export function StartClient(props: { router: AnyRouter }) {
  if (!props.router.state.lastUpdated) {
    props.router.hydrate()
  }

  return <RouterProvider router={props.router} />
}
