// benchmarks/client-nav/scenarios/interrupted-navigations/vue/src/app.tsx
import * as Vue from 'vue'
import { RouterProvider } from '@tanstack/vue-router'
import { getRouter } from './router'

export { interruptedNavigationRuntime } from './runtime'

export function mountTestApp(container: Element) {
  const router = getRouter()
  const component = <RouterProvider router={router} />
  const app = Vue.createApp({
    render: () => component,
  })
  let didUnmount = false

  app.mount(container)

  return {
    router,
    unmount() {
      if (didUnmount) {
        return
      }

      didUnmount = true
      app.unmount()
    },
  }
}

// benchmarks/client-nav/scenarios/history-events-blockers/react/src/app.tsx
import { RouterProvider } from '@tanstack/react-router'
import { createRoot } from 'react-dom/client'
import { getRouter } from './router'

export { historyEventsBlockersRuntime } from './runtime'

export function mountTestApp(container: Element) {
  const router = getRouter()
  const reactRoot = createRoot(container)
  let didUnmount = false
  reactRoot.render(<RouterProvider router={router} />)

  return {
    router,
    unmount() {
      if (didUnmount) {
        return
      }

      didUnmount = true
      reactRoot.unmount()
    },
  }
}
