// examples/solid/kitchen-sink-file-based/src/routes/(this-folder-is-not-in-the-url)/route-group.tsx
import { createFileRoute } from '@tanstack/solid-router'
import * as Solid from 'solid-js'

export const Route = createFileRoute('/(this-folder-is-not-in-the-url)/route-group')({
  component: RouteGroupExample,
})

function RouteGroupExample() {
  return (
    <div class={`p-2`}>
      <div class={`text-lg`}>Welcome to the Route Group Example!</div>
      <hr class={`my-2`} />
    </div>
  )
}

// examples/react/kitchen-sink-file-based/src/routes/(this-folder-is-not-in-the-url)/route-group.tsx
import * as React from 'react'
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute(
  '/(this-folder-is-not-in-the-url)/route-group',
)({
  component: RouteGroupExample,
})

function RouteGroupExample() {
  return (
    <div className={`p-2`}>
      <div className={`text-lg`}>Welcome to the Route Group Example!</div>
      <hr className={`my-2`} />
    </div>
  )
}
