// benchmarks/client-nav/scenarios/deferred-await/solid/src/routes/deferred.items.$itemId.details.tsx
import { createRoute } from '@tanstack/solid-router'
import {
  createDetailsLoaderData,
  deferredRouteGcTime,
  deferredRouteStaleTime,
} from '../../../shared'
import { DeferredValue } from '../deferred-value'
import { Route as itemRoute } from './deferred.items.$itemId'

export const Route = createRoute({
  getParentRoute: () => itemRoute,
  path: 'details',
  loader: ({ params }) => createDetailsLoaderData(params.itemId),
  staleTime: deferredRouteStaleTime(),
  gcTime: deferredRouteGcTime,
  component: DetailsPage,
})

function DetailsPage() {
  const data = Route.useLoaderData()

  return (
    <section data-deferred-page="details" data-deferred-id={data().critical.id}>
      <strong data-deferred-critical={data().critical.checksum}>
        {data().critical.label}
      </strong>
      <DeferredValue markerKey={data().detailsKey} promise={data().details} />
    </section>
  )
}

// benchmarks/client-nav/scenarios/deferred-await/vue/src/routes/deferred.items.$itemId.details.tsx
import * as Vue from 'vue'
import { createRoute } from '@tanstack/vue-router'
import {
  createDetailsLoaderData,
  deferredRouteGcTime,
  deferredRouteStaleTime,
  type DetailsLoaderData,
} from '../../../shared'
import { createDeferredValueNode } from '../deferred-value'
import { Route as itemRoute } from './deferred.items.$itemId'

const DetailsPage = Vue.defineComponent({
  setup() {
    const data = Route.useLoaderData() as Vue.Ref<DetailsLoaderData>

    return () => (
      <section
        data-deferred-page="details"
        data-deferred-id={data.value.critical.id}
      >
        <strong data-deferred-critical={data.value.critical.checksum}>
          {data.value.critical.label}
        </strong>
        {createDeferredValueNode(data.value.detailsKey, data.value.details)}
      </section>
    )
  },
})

export const Route = createRoute({
  getParentRoute: () => itemRoute,
  path: 'details',
  loader: ({ params }) => createDetailsLoaderData(params.itemId),
  staleTime: deferredRouteStaleTime(),
  gcTime: deferredRouteGcTime,
  component: DetailsPage,
})
