// packages/react-native-router/src/matchContext.tsx
import * as React from 'react'

export const matchContext = React.createContext<string | undefined>(undefined)

// N.B. this only exists so we can conditionally call useContext on it when we are not interested in the nearest match
export const dummyMatchContext = React.createContext<string | undefined>(
  undefined,
)

// packages/solid-router/src/matchContext.tsx
import * as Solid from 'solid-js'

export const matchContext = Solid.createContext<
  Solid.Accessor<string | undefined>
>(() => undefined)

// N.B. this only exists so we can conditionally call useContext on it when we are not interested in the nearest match
export const dummyMatchContext = Solid.createContext<
  Solid.Accessor<string | undefined>
>(() => undefined)
