// benchmarks/client-nav/scenarios/history-events-blockers/vue/src/routes/history.done.tsx
import * as Vue from 'vue'
import { createRoute } from '@tanstack/vue-router'
import {
  historyEventsBlockersDonePath,
  runHistoryEventsBlockersComputation,
} from '../../../shared.ts'
import { pathSeed } from '../runtime'
import { historyRoute } from './history'

const DonePage = Vue.defineComponent({
  setup() {
    return () => {
      void runHistoryEventsBlockersComputation(
        pathSeed(historyEventsBlockersDonePath),
      )

      return <main data-history-events-page="done" />
    }
  },
})

export const doneRoute = createRoute({
  getParentRoute: () => historyRoute,
  path: 'done',
  component: DonePage,
})

// benchmarks/client-nav/scenarios/history-events-blockers/solid/src/routes/history.done.tsx
import { createRoute } from '@tanstack/solid-router'
import {
  historyEventsBlockersDonePath,
  runHistoryEventsBlockersComputation,
} from '../../../shared.ts'
import { pathSeed } from '../runtime'
import { historyRoute } from './history'

export const doneRoute = createRoute({
  getParentRoute: () => historyRoute,
  path: 'done',
  component: DonePage,
})

function DonePage() {
  void runHistoryEventsBlockersComputation(
    pathSeed(historyEventsBlockersDonePath),
  )

  return <main data-history-events-page="done" />
}
