// examples/react/start-basic/app/client.tsx
import { hydrateRoot } from 'react-dom/client'
import { StartClient } from '@tanstack/start'
import { createRouter } from './router'

const router = createRouter()

// hydrateRoot(document, <StartClient router={router} />)
hydrateRoot(document.getElementById('root')!, <StartClient router={router} />)

// examples/solid/start-bare/app/client.tsx
/// <reference types="vinxi/types/client" />
import { StartClient } from '@tanstack/solid-start'

import { hydrate } from 'solid-js/web'
import { createRouter } from './router'

const router = createRouter()

const appDiv = document.getElementById('app')!

hydrate(() => <StartClient router={router} />, appDiv)
