// examples/react/with-loaders-code-split/src/routes/posts/post/Post.tsx
import * as React from 'react'
import { ComponentFromRoute, useRouteContext } from '@tanstack/router'
import { postRoute } from './postRoute'
import { useLoaderInstance } from '@tanstack/react-loaders'

export const Posts: ComponentFromRoute<typeof postRoute> = ({
  useRouteContext,
}) => {
  const { loaderOptions } = useRouteContext()
  const { data: post } = useLoaderInstance(loaderOptions)

  return (
    <div className="space-y-2">
      <h4 className="text-xl font-bold underline">{post.title}</h4>
      <div className="text-sm">{post.body}</div>
    </div>
  )
}

// examples/angular/basic/src/app/posts/post.ts
import { Component } from '@angular/core'
import { createRoute } from '@tanstack/angular-router'
import { fetchPost } from '../posts'
import { postsLayoutRoute } from './layout'

export const postRoute = createRoute({
  getParentRoute: () => postsLayoutRoute,
  path: '$postId',
  loader: ({ params }) => fetchPost(params.postId),
  component: () => PostComponent,
})

@Component({
  template: `
    <div class="space-y-2">
      <h4 class="text-xl font-bold">{{ post().title }}</h4>
      <hr class="opacity-20" />
      <div class="text-sm">{{ post().body }}</div>
    </div>
  `,
})
export class PostComponent {
  post = postRoute.loaderData()
}
