// packages/vue-router/src/ssr/RouterServer.tsx
import * as Vue from 'vue'
import { Asset } from '../Asset'
import { useTags } from '../HeadContent'
import { RouterProvider } from '../RouterProvider'
import { Scripts } from '../Scripts'
import type { AnyRouter } from '@tanstack/router-core'
import type { RouterManagedTag } from '@tanstack/router-core'

const ServerHeadContent = Vue.defineComponent({
  name: 'ServerHeadContent',
  setup() {
    const getTags = useTags()

    return () =>
      getTags().map((tag: RouterManagedTag) =>
        Vue.h(Asset, { key: tag.tag + (tag as any).id, ...tag }),
      )
  },
})

export const RouterServer = Vue.defineComponent({
  name: 'RouterServer',
  props: {
    router: {
      type: Object as () => AnyRouter,
      required: true,
    },
  },
  setup(props) {
    return () =>
      Vue.h('html', null, [
        Vue.h('head', null, [Vue.h(ServerHeadContent)]),
        Vue.h('body', null, [
          Vue.h(
            RouterProvider,
            {
              router: props.router,
            },
            {
              innerWrap: (innerProps: { children: any }) => [
                Vue.h(ServerHeadContent),
                innerProps.children,
                Vue.h(Scripts),
              ],
            },
          ),
        ]),
      ])
  },
})

// packages/solid-router/src/ssr/RouterServer.tsx
import {
  Hydration,
  HydrationScript,
  NoHydration,
  ssr,
  useAssets,
} from 'solid-js/web'
import { Asset } from '../Asset'
import { useTags } from '../HeadContent'
import { RouterProvider } from '../RouterProvider'
import { Scripts } from '../Scripts'
import type { AnyRouter } from '@tanstack/router-core'

export function ServerHeadContent() {
  const tags = useTags()
  useAssets(() => {
    return (
      <>
        {tags().map((tag) => (
          <Asset {...tag} />
        ))}
      </>
    )
  })
  return null
}

const docType = ssr('<!DOCTYPE html>')

export function RouterServer<TRouter extends AnyRouter>(props: {
  router: TRouter
}) {
  return (
    <NoHydration>
      {docType as any}
      <html>
        <head>
          <HydrationScript />
        </head>
        <body>
          <Hydration>
            <RouterProvider
              router={props.router}
              InnerWrap={(props) => (
                <NoHydration>
                  <ServerHeadContent />
                  <Hydration>{props.children}</Hydration>
                  <Scripts />
                </NoHydration>
              )}
            />
          </Hydration>
        </body>
      </html>
    </NoHydration>
  )
}
