// benchmarks/client-nav/scenarios/deferred-await/vue/src/deferred-value.tsx
import * as Vue from 'vue'
import { Await } from '@tanstack/vue-router'
import {
  deferredFallbackMarker,
  deferredResolvedMarker,
  type DeferredPayload,
} from '../../shared'

export function createDeferredValueNode(
  markerKey: string,
  promise: Promise<DeferredPayload>,
) {
  return (
    <Vue.Suspense>
      {{
        default: () => (
          <Await
            promise={promise}
            children={(payload: DeferredPayload) => (
              <span
                data-deferred-marker={deferredResolvedMarker(markerKey)}
                data-deferred-checksum={payload.checksum}
              >
                {payload.label}
              </span>
            )}
          />
        ),
        fallback: () => (
          <span data-deferred-marker={deferredFallbackMarker(markerKey)}>
            Loading {markerKey}
          </span>
        ),
      }}
    </Vue.Suspense>
  )
}

// benchmarks/client-nav/scenarios/deferred-await/solid/src/deferred-value.tsx
import { Suspense } from 'solid-js'
import { Await } from '@tanstack/solid-router'
import {
  deferredFallbackMarker,
  deferredResolvedMarker,
  type DeferredPayload,
} from '../../shared'

export function DeferredValue(props: {
  markerKey: string
  promise: Promise<DeferredPayload>
}) {
  return (
    <Suspense
      fallback={
        <span data-deferred-marker={deferredFallbackMarker(props.markerKey)}>
          Loading {props.markerKey}
        </span>
      }
    >
      <Await promise={props.promise}>
        {(payload) => (
          <span
            data-deferred-marker={deferredResolvedMarker(props.markerKey)}
            data-deferred-checksum={payload.checksum}
          >
            {payload.label}
          </span>
        )}
      </Await>
    </Suspense>
  )
}
