// benchmarks/client-nav/scenarios/head/solid/src/routes/docs.tsx
import { Outlet, createFileRoute } from '@tanstack/solid-router'
import { docsLayoutHead } from '../../../shared'

export const Route = createFileRoute('/docs')({
  head: docsLayoutHead,
  component: DocsLayout,
})

function DocsLayout() {
  return (
    <section>
      <h2>Docs</h2>
      <Outlet />
    </section>
  )
}

// benchmarks/client-nav/scenarios/head/vue/src/routes/docs.tsx
import * as Vue from 'vue'
import { Outlet, createFileRoute } from '@tanstack/vue-router'
import { docsLayoutHead } from '../../../shared'

const DocsLayout = Vue.defineComponent({
  setup() {
    return () => (
      <section>
        <h2>Docs</h2>
        <Outlet />
      </section>
    )
  },
})

export const Route = createFileRoute('/docs')({
  head: docsLayoutHead,
  component: DocsLayout,
})
