// benchmarks/client-nav/scenarios/head/vue/src/routes/docs.$section.tsx
import * as Vue from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import { docsDescription, docsSectionHead, docsTitle } from '../../../shared'

const DocsSectionPage = Vue.defineComponent({
  setup() {
    const params = Route.useParams()

    return () => (
      <article>
        <h1>{docsTitle(params.value.section)}</h1>
        <p>{docsDescription(params.value.section)}</p>
      </article>
    )
  },
})

export const Route = createFileRoute('/docs/$section')({
  head: ({ params }) => docsSectionHead(params.section),
  component: DocsSectionPage,
})

// benchmarks/client-nav/scenarios/head/solid/src/routes/docs.$section.tsx
import { createFileRoute } from '@tanstack/solid-router'
import { docsDescription, docsSectionHead, docsTitle } from '../../../shared'

export const Route = createFileRoute('/docs/$section')({
  head: ({ params }) => docsSectionHead(params.section),
  component: DocsSectionPage,
})

function DocsSectionPage() {
  const params = Route.useParams()

  return (
    <article>
      <h1>{docsTitle(params().section)}</h1>
      <p>{docsDescription(params().section)}</p>
    </article>
  )
}
