// benchmarks/client-nav/scenarios/head/vue/src/routes/settings.tsx
import * as Vue from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import { settingsHead, settingsTitle } from '../../../shared'

const SettingsPage = Vue.defineComponent({
  setup() {
    return () => (
      <main>
        <h1>{settingsTitle}</h1>
        <p>Account settings</p>
      </main>
    )
  },
})

export const Route = createFileRoute('/settings')({
  head: settingsHead,
  component: SettingsPage,
})

// benchmarks/client-nav/scenarios/head/solid/src/routes/settings.tsx
import { createFileRoute } from '@tanstack/solid-router'
import { settingsHead, settingsTitle } from '../../../shared'

export const Route = createFileRoute('/settings')({
  head: settingsHead,
  component: SettingsPage,
})

function SettingsPage() {
  return (
    <main>
      <h1>{settingsTitle}</h1>
      <p>Account settings</p>
    </main>
  )
}
