// examples/angular/basic/src/app/root.ts
import {
  DefaultNotFound,
  Link,
  Outlet,
  createRootRoute,
} from '@tanstack/angular-router'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { TanstackRouterDevtools } from '@tanstack/angular-router-devtools'

export const rootRoute = createRootRoute({
  component: () => Root,
  notFoundComponent: () => DefaultNotFound,
})

@Component({
  selector: 'Root',
  template: `
    <div class="p-2 flex gap-2 text-lg border-b">
      <a link="/" [linkActive]="{ exact: false }"> Home </a>
      <a link="/posts" linkActive="font-bold"> Posts </a>
      <a link="/route-a" linkActive="font-bold"> Pathless Layout </a>
      <a [link]="doesNotExist" linkActive="font-bold">
        This Route Does Not Exist
      </a>
    </div>
    <outlet />
    <TanstackRouterDevtools position="bottom-right" />
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [Link, Outlet, TanstackRouterDevtools],
})
export class Root {
  protected doesNotExist: any = '/this-route-does-not-exist'
}

// examples/react/basic-virtual-inside-file-based/src/routes/__root.tsx
import * as React from 'react'
import { Link, Outlet, createRootRoute } from '@tanstack/react-router'
import { TanStackRouterDevtools } from '@tanstack/react-router-devtools'

export const Route = createRootRoute({
  component: RootComponent,
  notFoundComponent: () => {
    return (
      <div>
        <p>This is the notFoundComponent configured on root route</p>
        <Link to="/">Start Over</Link>
      </div>
    )
  },
})

function RootComponent() {
  return (
    <>
      <div className="p-2 flex gap-2 text-lg border-b">
        <Link
          to="/"
          activeProps={{
            className: 'font-bold',
          }}
          activeOptions={{ exact: true }}
        >
          Home
        </Link>{' '}
        <Link
          to="/posts"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Posts
        </Link>{' '}
        <Link
          to="/layout-a"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Layout
        </Link>{' '}
        <Link
          to="/this-route-does-not-exist"
          activeProps={{
            className: 'font-bold',
          }}
        >
          This Route Does Not Exist
        </Link>
      </div>
      <hr />
      <Outlet />
      {/* Start rendering router matches */}
      <TanStackRouterDevtools position="bottom-right" />
    </>
  )
}
