// benchmarks/client-nav/scenarios/async-pipeline/react/src/routes/slow.$id.tsx
import { createFileRoute } from '@tanstack/react-router'
import { deferredHops, hopDelay, slowStateValue } from '../../../shared'

export const Route = createFileRoute('/slow/$id')({
  staleTime: 0,
  gcTime: 0,
  loader: async ({ params }) => {
    await hopDelay(deferredHops)
    return { value: slowStateValue(params.id) }
  },
  component: SlowPage,
})

function SlowPage() {
  const data = Route.useLoaderData()

  return <div data-testid="slow-state">{data.value}</div>
}

// benchmarks/client-nav/scenarios/async-pipeline/vue/src/routes/slow.$id.tsx
import * as Vue from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import { deferredHops, hopDelay, slowStateValue } from '../../../shared'

const SlowPage = Vue.defineComponent({
  setup() {
    const data = Route.useLoaderData()

    return () => <div data-testid="slow-state">{data.value.value}</div>
  },
})

export const Route = createFileRoute('/slow/$id')({
  staleTime: 0,
  gcTime: 0,
  loader: async ({ params }) => {
    await hopDelay(deferredHops)
    return { value: slowStateValue(params.id) }
  },
  component: SlowPage,
})
