// benchmarks/client-nav/scenarios/mount/vue/src/routes/shop.$productId.tsx
import * as Vue from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import { productData } from '../../../shared'

const ProductPage = Vue.defineComponent({
  setup() {
    const product = Route.useLoaderData()

    return () => (
      <article>{`${product.value.name}: ${product.value.price}`}</article>
    )
  },
})

export const Route = createFileRoute('/shop/$productId')({
  loader: ({ params }) => productData(params.productId),
  component: ProductPage,
})

// benchmarks/client-nav/scenarios/mount/solid/src/routes/shop.$productId.tsx
import { createFileRoute } from '@tanstack/solid-router'
import { productData } from '../../../shared'

export const Route = createFileRoute('/shop/$productId')({
  loader: ({ params }) => productData(params.productId),
  component: ProductPage,
})

function ProductPage() {
  const product = Route.useLoaderData()

  return <article>{`${product().name}: ${product().price}`}</article>
}
