// benchmarks/client-nav/scenarios/before-load-context/solid/src/routes/app.$orgId.projects.tsx
import { Outlet, createFileRoute } from '@tanstack/solid-router'
import {
  consumeSelectedValue,
  deriveProjectsContext,
  runContextComputation,
} from '../../../shared'
import { PerfValue } from '../runtime'

export const Route = createFileRoute('/app/$orgId/projects')({
  beforeLoad: ({ context }) => deriveProjectsContext(context),
  component: ProjectsLayout,
})

function ProjectsLayout() {
  const value = Route.useRouteContext({
    select: (context) =>
      runContextComputation(
        context.projectIndexSeed,
        context.breadcrumb[2],
        10,
      ),
  })

  return (
    <>
      <PerfValue
        value={() =>
          consumeSelectedValue(value(), 'projects-context-subscriber')
        }
      />
      <Outlet />
    </>
  )
}

// benchmarks/client-nav/scenarios/before-load-context/vue/src/routes/app.$orgId.projects.tsx
import * as Vue from 'vue'
import { Outlet, createFileRoute } from '@tanstack/vue-router'
import { deriveProjectsContext, runContextComputation } from '../../../shared'
import { consumeSelectedValue } from '../runtime'

const ProjectsLayout = Vue.defineComponent({
  setup() {
    const value = Route.useRouteContext({
      select: (context) =>
        runContextComputation(
          context.projectIndexSeed,
          context.breadcrumb[2],
          10,
        ),
    })

    return () => {
      consumeSelectedValue(value.value, 'projects-context-subscriber')
      return <Outlet />
    }
  },
})

export const Route = createFileRoute('/app/$orgId/projects')({
  beforeLoad: ({ context }) => deriveProjectsContext(context),
  component: ProjectsLayout,
})
