// benchmarks/client-nav/scenarios/nested-params/react/src/routes/l.$a.$b.$c.tsx
import { Outlet, createFileRoute } from '@tanstack/react-router'
import { normalizeParam, smallHash } from '../../../shared'

export const Route = createFileRoute('/l/$a/$b/$c')({
  params: {
    parse: (params) => ({ ...params, c: normalizeParam(params.c) }),
    stringify: (params) => ({ ...params, c: String(params.c) }),
  },
  beforeLoad: ({ params }) => ({ ctxC: smallHash(params.c) }),
  component: LevelC,
})

function ParamsSubscriberOne() {
  const value = Route.useParams({ select: (params) => smallHash(params.c) })
  void value
  return null
}

function ParamsSubscriberTwo() {
  const value = Route.useParams({
    select: (params) => smallHash(`${params.c}:2`),
  })
  void value
  return null
}

function ContextSubscriberOne() {
  const value = Route.useRouteContext({ select: (context) => context.ctxC })
  void value
  return null
}

function ContextSubscriberTwo() {
  const value = Route.useRouteContext({
    select: (context) => (context.ctxC * 31 + 7) >>> 0,
  })
  void value
  return null
}

function LevelC() {
  return (
    <>
      <ParamsSubscriberOne />
      <ParamsSubscriberTwo />
      <ContextSubscriberOne />
      <ContextSubscriberTwo />
      <Outlet />
    </>
  )
}

// benchmarks/client-nav/scenarios/nested-params/vue/src/routes/l.$a.$b.$c.tsx
import * as Vue from 'vue'
import { Outlet, createFileRoute } from '@tanstack/vue-router'
import { normalizeParam, smallHash } from '../../../shared'

const ParamsSubscriberOne = Vue.defineComponent({
  setup() {
    const value = Route.useParams({
      select: (params) => smallHash(params.c),
    })
    return () => {
      void value.value
      return null
    }
  },
})

const ParamsSubscriberTwo = Vue.defineComponent({
  setup() {
    const value = Route.useParams({
      select: (params) => smallHash(`${params.c}:2`),
    })
    return () => {
      void value.value
      return null
    }
  },
})

const ContextSubscriberOne = Vue.defineComponent({
  setup() {
    const value = Route.useRouteContext({
      select: (context) => context.ctxC,
    })
    return () => {
      void value.value
      return null
    }
  },
})

const ContextSubscriberTwo = Vue.defineComponent({
  setup() {
    const value = Route.useRouteContext({
      select: (context) => (context.ctxC * 31 + 7) >>> 0,
    })
    return () => {
      void value.value
      return null
    }
  },
})

const LevelC = Vue.defineComponent({
  setup() {
    return () => (
      <>
        <ParamsSubscriberOne />
        <ParamsSubscriberTwo />
        <ContextSubscriberOne />
        <ContextSubscriberTwo />
        <Outlet />
      </>
    )
  },
})

export const Route = createFileRoute('/l/$a/$b/$c')({
  params: {
    parse: (params) => ({ ...params, c: normalizeParam(params.c) }),
    stringify: (params) => ({ ...params, c: String(params.c) }),
  },
  beforeLoad: ({ params }) => ({ ctxC: smallHash(params.c) }),
  component: LevelC,
})
