// examples/angular/basic-file-based/src/routes/_pathlessLayout/_nested-layout/route-a.ts
import { Component } from '@angular/core'
import { createFileRoute } from '@tanstack/angular-router-experimental'

export const Route = createFileRoute('/_pathlessLayout/_nested-layout/route-a')({
  component: () => RouteAComponent,
})

@Component({
  selector: 'route-component',
  standalone: true,
  template: `<div>I'm layout A!</div>`,
})
class RouteAComponent {}

// examples/react/start-basic-netlify/src/routes/_pathlessLayout/_nested-layout/route-a.tsx
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_pathlessLayout/_nested-layout/route-a')(
  {
    component: LayoutAComponent,
  },
)

/**
 * Renders the layout A component showing "I'm A!".
 *
 * @returns A JSX element containing a div with the text "I'm A!".
 */
function LayoutAComponent() {
  return <div>I'm A!</div>
}
