// benchmarks/client-nav/scenarios/links/vue/src/routes/about.tsx
import * as Vue from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import { aboutMarker } from '../../../shared'

const AboutPage = Vue.defineComponent({
  setup() {
    return () => (
      <main>
        <p data-testid="page-state">{aboutMarker}</p>
      </main>
    )
  },
})

export const Route = createFileRoute('/about')({
  component: AboutPage,
})

// examples/vue/start-bun-bundler/src/routes/about.tsx
import { createFileRoute } from '@tanstack/vue-router'

export const Route = createFileRoute('/about')({
  component: About,
})

function About() {
  return (
    <main style={{ fontFamily: 'system-ui', padding: '24px' }}>
      <h1>About</h1>
      <p>Second route to exercise Bun code-splitting.</p>
      <p>
        <a href="/">Home</a>
      </p>
    </main>
  )
}
