// benchmarks/client-nav/scenarios/outlets-remounts/react/src/routes/workspace.$orgId.projects.$projectId.tsx
import { Outlet, createRoute } from '@tanstack/react-router'
import { createOutletsRemountsProjectMarker } from '../../../shared'
import { createRouteLifecycleOptions } from '../outletsRemountsRuntime'
import { RouteShell } from '../routeShell'
import { projectsRoute } from './workspace.$orgId.projects'

function ProjectLayout() {
  const params = projectRoute.useParams()
  const marker = createOutletsRemountsProjectMarker(params)

  return (
    <RouteShell routeId="project" marker={marker}>
      <Outlet />
    </RouteShell>
  )
}

export const projectRoute = createRoute({
  getParentRoute: () => projectsRoute,
  path: '$projectId',
  ...createRouteLifecycleOptions('project'),
  remountDeps: ({ params }) => ({
    projectId: params.projectId,
  }),
  component: ProjectLayout,
})

// benchmarks/client-nav/scenarios/outlets-remounts/vue/src/routes/workspace.$orgId.projects.$projectId.tsx
import * as Vue from 'vue'
import { Outlet, createRoute, useParams } from '@tanstack/vue-router'
import { createOutletsRemountsProjectMarker } from '../../../shared'
import {
  createRouteLifecycleOptions,
  recordComponentMount,
} from '../outletsRemountsRuntime'
import { createRouteSection } from '../routeSection'
import { projectsRoute } from './workspace.$orgId.projects'

const ProjectLayout = Vue.defineComponent({
  setup() {
    const params = useParams({ strict: false })
    const getMarker = () => createOutletsRemountsProjectMarker(params.value)
    const mountIndex = recordComponentMount('project', getMarker())

    return () =>
      createRouteSection('project', getMarker(), mountIndex, <Outlet />)
  },
})

export const projectRoute = createRoute({
  getParentRoute: () => projectsRoute,
  path: '$projectId',
  ...createRouteLifecycleOptions('project'),
  remountDeps: ({ params }) => ({
    projectId: params.projectId,
  }),
  component: ProjectLayout,
})
