// benchmarks/client-nav/scenarios/outlets-remounts/solid/src/routes/workspace.$orgId.projects.$projectId.boards.$boardId.tsx
import { Outlet, createRoute } from '@tanstack/solid-router'
import { createOutletsRemountsBoardMarker } from '../../../shared'
import { createRouteLifecycleOptions } from '../outletsRemountsRuntime'
import { RouteShell } from '../routeShell'
import { projectRoute } from './workspace.$orgId.projects.$projectId'

function BoardLayout() {
  const params = boardRoute.useParams()
  const marker = () => createOutletsRemountsBoardMarker(params())

  return (
    <RouteShell routeId="board" marker={marker}>
      <Outlet />
    </RouteShell>
  )
}

export const boardRoute = createRoute({
  getParentRoute: () => projectRoute,
  path: 'boards/$boardId',
  ...createRouteLifecycleOptions('board'),
  remountDeps: ({ params }) => ({
    boardId: params.boardId,
  }),
  component: BoardLayout,
})

// benchmarks/client-nav/scenarios/outlets-remounts/vue/src/routes/workspace.$orgId.projects.$projectId.boards.$boardId.tsx
import * as Vue from 'vue'
import { Outlet, createRoute, useParams } from '@tanstack/vue-router'
import { createOutletsRemountsBoardMarker } from '../../../shared'
import {
  createRouteLifecycleOptions,
  recordComponentMount,
} from '../outletsRemountsRuntime'
import { createRouteSection } from '../routeSection'
import { projectRoute } from './workspace.$orgId.projects.$projectId'

const BoardLayout = Vue.defineComponent({
  setup() {
    const params = useParams({ strict: false })
    const getMarker = () => createOutletsRemountsBoardMarker(params.value)
    const mountIndex = recordComponentMount('board', getMarker())

    return () =>
      createRouteSection('board', getMarker(), mountIndex, <Outlet />)
  },
})

export const boardRoute = createRoute({
  getParentRoute: () => projectRoute,
  path: 'boards/$boardId',
  ...createRouteLifecycleOptions('board'),
  remountDeps: ({ params }) => ({
    boardId: params.boardId,
  }),
  component: BoardLayout,
})
