// benchmarks/client-nav/scenarios/interrupted-navigations/vue/src/routes/fast.tsx
import * as Vue from 'vue'
import { createRoute } from '@tanstack/vue-router'
import {
  interruptedNavigationRuntime,
  recordInterruptedCommit,
} from '../runtime'
import { interruptRoute } from './interrupt'

const FastPage: ReturnType<typeof Vue.defineComponent> = Vue.defineComponent({
  setup() {
    const data = fastRoute.useLoaderData()

    return () => {
      recordInterruptedCommit(data.value)

      return (
        <main data-interrupted-id={data.value.id} data-interrupted-page="fast">
          {`${data.value.kind}:${data.value.id}:${data.value.sequence}:${data.value.checksum}`}
        </main>
      )
    }
  },
})

export const fastRoute = createRoute({
  getParentRoute: () => interruptRoute,
  path: 'fast/$id',
  loader: ({ params }) =>
    interruptedNavigationRuntime.recordFastLoad(params.id),
  staleTime: 0,
  gcTime: 0,
  component: FastPage,
})

// benchmarks/client-nav/scenarios/interrupted-navigations/solid/src/routes/fast.tsx
import { createRoute } from '@tanstack/solid-router'
import { CommitEffect, interruptedNavigationRuntime } from '../runtime'
import { interruptRoute } from './interrupt'

export const fastRoute = createRoute({
  getParentRoute: () => interruptRoute,
  path: 'fast/$id',
  loader: ({ params }) =>
    interruptedNavigationRuntime.recordFastLoad(params.id),
  staleTime: 0,
  gcTime: 0,
  component: FastPage,
})

function FastPage() {
  const data = fastRoute.useLoaderData()

  return (
    <main data-interrupted-id={data().id} data-interrupted-page="fast">
      <CommitEffect payload={data()} />
      {`${data().kind}:${data().id}:${data().sequence}:${data().checksum}`}
    </main>
  )
}
