// benchmarks/client-nav/scenarios/before-load-context/vue/src/routes/app.$orgId.projects.$projectId.tasks.tsx
import * as Vue from 'vue'
import { Outlet, createFileRoute } from '@tanstack/vue-router'
import { deriveTaskListContext, runContextComputation } from '../../../shared'
import { consumeSelectedValue } from '../runtime'

const TasksLayout = Vue.defineComponent({
  setup() {
    const value = Route.useRouteContext({
      select: (context) =>
        runContextComputation(context.taskListSeed, context.taskScope, 10),
    })

    return () => {
      consumeSelectedValue(value.value, 'tasks-context-subscriber')
      return <Outlet />
    }
  },
})

export const Route = createFileRoute('/app/$orgId/projects/$projectId/tasks')({
  beforeLoad: ({ context }) => deriveTaskListContext(context),
  component: TasksLayout,
})

// benchmarks/client-nav/scenarios/before-load-context/react/src/routes/app.$orgId.projects.$projectId.tasks.tsx
import { Outlet, createFileRoute } from '@tanstack/react-router'
import { deriveTaskListContext, runContextComputation } from '../../../shared'
import { consumeSelectedValue } from '../runtime'

export const Route = createFileRoute('/app/$orgId/projects/$projectId/tasks')({
  beforeLoad: ({ context }) => deriveTaskListContext(context),
  component: TasksLayout,
})

function TasksLayout() {
  const value = Route.useRouteContext({
    select: (context) =>
      runContextComputation(context.taskListSeed, context.taskScope, 10),
  })

  consumeSelectedValue(value, 'tasks-context-subscriber')
  return <Outlet />
}
