// benchmarks/memory/server/scenarios/aborted-requests/react/src/routes/stream.$id.tsx
import { Await, createFileRoute } from '@tanstack/react-router'
import { Suspense } from 'react'
import { makeAbortedRequestRecords } from '../../../deferred-records'

function resolveAfterMicrotasks<T>(microtasks: number, value: () => T) {
  let promise = Promise.resolve()

  for (let index = 0; index < microtasks; index++) {
    promise = promise.then(() => undefined)
  }

  return promise.then(value)
}

export const Route = createFileRoute('/stream/$id')({
  loader: ({ params }) => ({
    eager: `eager-${params.id}`,
    alpha: resolveAfterMicrotasks(32, () =>
      makeAbortedRequestRecords(params.id, 'alpha'),
    ),
    beta: resolveAfterMicrotasks(64, () =>
      makeAbortedRequestRecords(params.id, 'beta'),
    ),
  }),
  component: StreamComponent,
})

function StreamComponent() {
  const data = Route.useLoaderData()

  return (
    <main data-bench="aborted-requests-stream">
      <p data-bench="aborted-requests-eager">{data.eager}</p>
      <Suspense
        fallback={
          <p data-bench="aborted-requests-alpha-fallback">loading-alpha</p>
        }
      >
        <Await promise={data.alpha}>
          {(records) => (
            <ul data-bench="aborted-requests-alpha">
              {records.map((record) => (
                <li key={record.id}>{record.label}</li>
              ))}
            </ul>
          )}
        </Await>
      </Suspense>
      <Suspense
        fallback={
          <p data-bench="aborted-requests-beta-fallback">loading-beta</p>
        }
      >
        <Await promise={data.beta}>
          {(records) => (
            <ul data-bench="aborted-requests-beta">
              {records.map((record) => (
                <li key={record.id}>{record.label}</li>
              ))}
            </ul>
          )}
        </Await>
      </Suspense>
    </main>
  )
}

// benchmarks/memory/server/scenarios/aborted-requests/vue/src/routes/stream.$id.tsx
import { createServerOnlyFn } from '@tanstack/vue-start'
import { getRequest } from '@tanstack/vue-start/server'
import { Await, createFileRoute } from '@tanstack/vue-router'
import { Suspense } from 'vue'
import { makeDeferredRecords } from '../../../deferred-records'
import type { DeferredRecord } from '../../../deferred-records'

const getRequestSignal = createServerOnlyFn(() => getRequest().signal)

export const Route = createFileRoute('/stream/$id')({
  loader: ({ params }) => ({
    eager: `eager-${params.id}`,
    alpha: makeDeferredRecords(params.id, 'alpha', getRequestSignal()),
    beta: makeDeferredRecords(params.id, 'beta', getRequestSignal()),
  }),
  component: StreamComponent,
})

function StreamComponent() {
  const data = Route.useLoaderData()

  return (
    <main data-bench="aborted-requests-stream">
      <p data-bench="aborted-requests-eager">{data.value.eager}</p>
      <p data-bench="aborted-requests-alpha-fallback">loading-alpha</p>
      <p data-bench="aborted-requests-beta-fallback">loading-beta</p>
      <Suspense>
        {{
          default: () => (
            <Await
              promise={data.value.alpha}
              children={(records: Array<DeferredRecord>) => (
                <ul data-bench="aborted-requests-alpha">
                  {records.map((record) => (
                    <li key={record.id}>{record.label}</li>
                  ))}
                </ul>
              )}
            />
          ),
          fallback: () => null,
        }}
      </Suspense>
      <Suspense>
        {{
          default: () => (
            <Await
              promise={data.value.beta}
              children={(records: Array<DeferredRecord>) => (
                <ul data-bench="aborted-requests-beta">
                  {records.map((record) => (
                    <li key={record.id}>{record.label}</li>
                  ))}
                </ul>
              )}
            />
          ),
          fallback: () => null,
        }}
      </Suspense>
    </main>
  )
}
