// examples/solid/start-convex-better-auth/src/components/Counter.tsx
import { createSignal } from 'solid-js'
import './Counter.css'

export default function Counter() {
  const [count, setCount] = createSignal(0)
  return (
    <button
      class="increment"
      onClick={() => setCount(count() + 1)}
      type="button"
    >
      Clicks: {count()}
    </button>
  )
}

// examples/react/wip-waku-rsc/src/components/Counter.tsx
"use client";

import { useState } from "react";

export const Counter = () => {
  const [count, setCount] = useState(0);
  return (
    <div style={{ border: "3px blue dashed", margin: "1em", padding: "1em" }}>
      <p>Count: {count}</p>
      <button onClick={() => setCount((c) => c + 1)}>Increment</button>
      <h3>This is a client component.</h3>
    </div>
  );
};
