// benchmarks/client-nav/scenarios/mount/react/src/routes/shop.tsx
import { Outlet, createFileRoute } from '@tanstack/react-router'
import { shopContext } from '../../../shared'

export const Route = createFileRoute('/shop')({
  beforeLoad: () => shopContext(),
  component: ShopLayout,
})

function ShopLayout() {
  return (
    <section>
      <h2>Shop</h2>
      <Outlet />
    </section>
  )
}

// benchmarks/client-nav/scenarios/mount/vue/src/routes/shop.tsx
import * as Vue from 'vue'
import { Outlet, createFileRoute } from '@tanstack/vue-router'
import { shopContext } from '../../../shared'

const ShopLayout = Vue.defineComponent({
  setup() {
    return () => (
      <section>
        <h2>Shop</h2>
        <Outlet />
      </section>
    )
  },
})

export const Route = createFileRoute('/shop')({
  beforeLoad: () => shopContext(),
  component: ShopLayout,
})
