// benchmarks/client-nav/scenarios/hydration-resume/vue/src/perf.tsx
import * as Vue from 'vue'
import {
  runHydrationResumeComputation,
  type HydrationResumeDeferredPayload,
} from '../../shared.ts'

export const subscriberSlots = Array.from({ length: 4 }, (_, index) => index)

export const PerfSubscriber = Vue.defineComponent({
  props: {
    seed: {
      type: Number,
      required: true,
    },
  },
  setup(props) {
    return () => {
      void runHydrationResumeComputation(props.seed)
      return null
    }
  },
})

export const DeferredResolved = Vue.defineComponent({
  props: {
    payload: {
      type: Object as () => HydrationResumeDeferredPayload,
      required: true,
    },
    source: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    return () => {
      void runHydrationResumeComputation(props.payload.checksum)

      return (
        <div
          data-hydration-resume-marker="deferred-resolved"
          data-item-id={props.payload.itemId}
          data-source={props.source}
          data-value={props.payload.value}
        />
      )
    }
  },
})

// benchmarks/client-nav/scenarios/hydration-resume/react/src/perf.tsx
import {
  runHydrationResumeComputation,
  type HydrationResumeDeferredPayload,
} from '../../shared.ts'

export const subscriberSlots = Array.from({ length: 4 }, (_, index) => index)

export function PerfSubscriber({ seed }: { seed: number }) {
  void runHydrationResumeComputation(seed)
  return null
}

export function DeferredResolved({
  payload,
  source,
}: {
  payload: HydrationResumeDeferredPayload
  source: string
}) {
  void runHydrationResumeComputation(payload.checksum)

  return (
    <div
      data-hydration-resume-marker="deferred-resolved"
      data-item-id={payload.itemId}
      data-source={source}
      data-value={payload.value}
    />
  )
}
