// benchmarks/client-nav/scenarios/outlets-remounts/vue/src/routes/workspace.$orgId.projects.tsx
import * as Vue from 'vue'
import { Outlet, createRoute, useParams } from '@tanstack/vue-router'
import { createOutletsRemountsProjectsMarker } from '../../../shared'
import {
  createRouteLifecycleOptions,
  recordComponentMount,
} from '../outletsRemountsRuntime'
import { createRouteSection } from '../routeSection'
import { orgRoute } from './workspace.$orgId'

const ProjectsLayout = Vue.defineComponent({
  setup() {
    const params = useParams({ strict: false })
    const getMarker = () => createOutletsRemountsProjectsMarker(params.value)
    const mountIndex = recordComponentMount('projects', getMarker())

    return () =>
      createRouteSection('projects', getMarker(), mountIndex, <Outlet />)
  },
})

export const projectsRoute = createRoute({
  getParentRoute: () => orgRoute,
  path: 'projects',
  ...createRouteLifecycleOptions('projects'),
  component: ProjectsLayout,
})

// benchmarks/client-nav/scenarios/outlets-remounts/solid/src/routes/workspace.$orgId.projects.tsx
import { Outlet, createRoute } from '@tanstack/solid-router'
import { createOutletsRemountsProjectsMarker } from '../../../shared'
import { createRouteLifecycleOptions } from '../outletsRemountsRuntime'
import { RouteShell } from '../routeShell'
import { orgRoute } from './workspace.$orgId'

function ProjectsLayout() {
  const params = projectsRoute.useParams()
  const marker = () => createOutletsRemountsProjectsMarker(params())

  return (
    <RouteShell routeId="projects" marker={marker}>
      <Outlet />
    </RouteShell>
  )
}

export const projectsRoute = createRoute({
  getParentRoute: () => orgRoute,
  path: 'projects',
  ...createRouteLifecycleOptions('projects'),
  component: ProjectsLayout,
})
