// benchmarks/client-nav/scenarios/loader-cache/solid/src/app.tsx
import { render } from 'solid-js/web'
import { RouterProvider } from '@tanstack/solid-router'
import { getRouter } from './router'

export { loaderCacheRuntime } from './runtime'

export function mountTestApp(container: Element) {
  const router = getRouter()
  const dispose = render(() => <RouterProvider router={router} />, container)
  let didUnmount = false

  return {
    router,
    unmount() {
      if (didUnmount) {
        return
      }

      didUnmount = true
      dispose()
    },
  }
}

// benchmarks/client-nav/scenarios/interrupted-navigations/vue/src/app.tsx
import * as Vue from 'vue'
import { RouterProvider } from '@tanstack/vue-router'
import { getRouter } from './router'

export { interruptedNavigationRuntime } from './runtime'

export function mountTestApp(container: Element) {
  const router = getRouter()
  const component = <RouterProvider router={router} />
  const app = Vue.createApp({
    render: () => component,
  })
  let didUnmount = false

  app.mount(container)

  return {
    router,
    unmount() {
      if (didUnmount) {
        return
      }

      didUnmount = true
      app.unmount()
    },
  }
}
