// benchmarks/ssr/scenarios/serialization/vue/src/routes/rich.$id.tsx
import { defineComponent } from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import { makeRichSerializationData } from '../../../shared-data'

const RichComponent = defineComponent({
  setup() {
    const data = Route.useLoaderData()

    return () => (
      <section>
        <h1>{data.value.label}</h1>
        <p>{data.value.createdAt.toISOString()}</p>
        <p>{data.value.lookup.get('k0')?.label}</p>
        <p>{Array.from(data.value.tags)[0]}</p>
        <p>{data.value.count.toString()}</p>
        <p>{data.value.nested[0]?.id}</p>
        <p>{data.value.points[0]?.label}</p>
        <p>{data.value.problem.message}</p>
      </section>
    )
  },
})

export const Route = createFileRoute('/rich/$id')({
  loader: ({ params }) => makeRichSerializationData(params.id),
  component: RichComponent,
})

// benchmarks/ssr/scenarios/serialization/solid/src/routes/rich.$id.tsx
import { createFileRoute } from '@tanstack/solid-router'
import { makeRichSerializationData } from '../../../shared-data'

export const Route = createFileRoute('/rich/$id')({
  loader: ({ params }) => makeRichSerializationData(params.id),
  component: RichComponent,
})

function RichComponent() {
  const data = Route.useLoaderData()
  const firstMapEntry = () => data().lookup.get('k0')
  const firstTag = () => Array.from(data().tags)[0]

  return (
    <section>
      <h1>{data().label}</h1>
      <p>{data().createdAt.toISOString()}</p>
      <p>{firstMapEntry()?.label}</p>
      <p>{firstTag()}</p>
      <p>{data().count.toString()}</p>
      <p>{data().nested[0]?.id}</p>
      <p>{data().points[0]?.label}</p>
      <p>{data().problem.message}</p>
    </section>
  )
}
