// examples/react/start-i18n-intlayer/src/components/locale-switcher.tsx
import { useLocation } from '@tanstack/react-router'
import {
  getHTMLTextDir,
  getLocaleName,
  getPathWithoutLocale,
  getPrefix,
} from 'intlayer'
import { setLocaleInStorage, useIntlayer, useLocale } from 'react-intlayer'

import { LocalizedLink } from './localized-link'
import type { To } from './localized-link'
import type { FC } from 'react'

export const LocaleSwitcher: FC = () => {
  const { localeSwitcherLabel } = useIntlayer('locale-switcher')
  const { pathname } = useLocation()

  const { availableLocales, locale } = useLocale()

  const pathWithoutLocale = getPathWithoutLocale(pathname)

  return (
    <ol className="divide-text/20 divide-y divide-dashed rounded-2xl bg-cyan-600 overflow-y-auto p-1 absolute top-10 right-10">
      {availableLocales.map((localeEl) => (
        <li className="py-1" key={localeEl}>
          <LocalizedLink
            aria-current={localeEl === locale ? 'page' : undefined}
            aria-label={
              localeSwitcherLabel({ language: getLocaleName(localeEl) }).value
            }
            onClick={() => setLocaleInStorage(localeEl)}
            params={{ locale: getPrefix(localeEl).localePrefix }}
            to={pathWithoutLocale as To}
          >
            <div className="flex flex-row items-center hover:bg-cyan-700 text-white rounded-md justify-between gap-3 px-2 py-1">
              <div className="flex flex-col text-nowrap">
                <span dir={getHTMLTextDir(localeEl)} lang={localeEl}>
                  {getLocaleName(localeEl)}
                </span>
                <span className="text-neutral text-xs">
                  {getLocaleName(localeEl, localeEl)}
                </span>
              </div>
              <span className="text-neutral text-sm text-nowrap">
                {localeEl.toUpperCase()}
              </span>
            </div>
          </LocalizedLink>
        </li>
      ))}
    </ol>
  )
}

// examples/solid/start-i18n-intlayer/src/components/LocaleSwitcher.tsx
import { useLocation } from '@tanstack/solid-router'
import { getLocaleName, getPathWithoutLocale, getPrefix } from 'intlayer'
import { For } from 'solid-js'
import { useIntlayer, useLocale } from 'solid-intlayer'
import { Link, type To } from './LocalizedLink'

export const LocaleSwitcher = () => {
  const content = useIntlayer('locale-switcher')
  const location = useLocation()

  const { availableLocales, locale, setLocale } = useLocale()

  const pathWithoutLocale = () => getPathWithoutLocale(location().pathname)

  return (
    <div class="flex flex-row gap-2">
      <For each={availableLocales}>
        {(localeEl) => (
          <h2 class="m-0 flex-shrink-0 text-base font-semibold tracking-tight">
            <Link
              aria-current={localeEl === locale() ? 'page' : undefined}
              aria-label={
                content().localeSwitcherLabel({
                  language: getLocaleName(localeEl),
                }).value
              }
              onClick={() => setLocale(localeEl)}
              params={{ locale: getPrefix(localeEl).localePrefix }}
              to={pathWithoutLocale() as To}
              class="brand-pill"
              activeProps={{
                class: 'brand-pill opacity-50 pointer-events-none',
              }}
            >
              {getLocaleName(localeEl)}
            </Link>
          </h2>
        )}
      </For>
    </div>
  )
}
