// examples/react/basic-file-based/src/routes/_layout.tsx
import * as React from 'react'
import { Outlet, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_layout')({
  component: LayoutComponent,
})

function LayoutComponent() {
  return (
    <div>
      <div>I'm a layout</div>
      <div>
        <Outlet />
      </div>
    </div>
  )
}

// examples/solid/kitchen-sink-file-based/src/routes/_layout.tsx
import * as React from 'solid-js'
import { Outlet, createFileRoute } from '@tanstack/solid-router'

export const Route = createFileRoute('/_layout')({
  component: LayoutComponent,
})

function LayoutComponent() {
  return (
    <div>
      <div>Layout</div>
      <hr />
      <Outlet />
    </div>
  )
}
