// packages/react-router/examples/react/with-trpc/src/routes/dashboard.index.tsx
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/dashboard/')({
  loader: ({ context: { trpc } }) => trpc.posts.query(),
  component: DashboardIndexComponent,
})

function DashboardIndexComponent() {
  const posts = Route.useLoaderData()

  return (
    <div className="p-2">
      <div className="p-2">
        Welcome to the dashboard! You have{' '}
        <strong>{posts.length} total posts</strong>.
      </div>
    </div>
  )
}

// examples/solid/kitchen-sink-file-based/src/routes/dashboard.index.tsx
import * as Solid from 'solid-js'
import { createFileRoute } from '@tanstack/solid-router'
import { fetchInvoices } from '../utils/mockTodos'

export const Route = createFileRoute('/dashboard/')({
  loader: () => fetchInvoices(),
  component: DashboardIndexComponent,
})

function DashboardIndexComponent() {
  const invoices = Route.useLoaderData()

  return (
    <div class="p-2">
      <div class="p-2">
        Welcome to the dashboard! You have{' '}
        <strong>{invoices.length} total invoices</strong>.
      </div>
    </div>
  )
}
