// benchmarks/ssr/scenarios/assets/vue/src/routes/a.$x.$y.tsx
import { defineComponent } from 'vue'
import { createFileRoute } from '@tanstack/vue-router'
import '../styles/assets-leaf.css'

const LeafComponent = defineComponent({
  setup() {
    const params = Route.useParams()

    return () => (
      <section class="assets-leaf">
        <p>
          assets-leaf-{params.value.x}-{params.value.y}
        </p>
      </section>
    )
  },
})

export const Route = createFileRoute('/a/$x/$y')({
  head: ({ params }) => ({
    meta: [{ title: `SSR Assets ${params.x} ${params.y}` }],
    links: Array.from({ length: 3 }, (_, index) => ({
      rel: 'preload',
      as: 'image',
      href: `/asset-preload/${params.y}-${index}.png`,
    })),
  }),
  component: LeafComponent,
})

// benchmarks/ssr/scenarios/assets/react/src/routes/a.$x.$y.tsx
import { createFileRoute } from '@tanstack/react-router'
import '../styles/assets-leaf.css'

export const Route = createFileRoute('/a/$x/$y')({
  head: ({ params }) => ({
    meta: [{ title: `SSR Assets ${params.x} ${params.y}` }],
    links: Array.from({ length: 3 }, (_, index) => ({
      rel: 'preload',
      as: 'image',
      href: `/asset-preload/${params.y}-${index}.png`,
    })),
  }),
  component: LeafComponent,
})

function LeafComponent() {
  const { x, y } = Route.useParams()

  return (
    <section className="assets-leaf">
      <p>
        assets-leaf-{x}-{y}
      </p>
    </section>
  )
}
