// examples/solid/basic/src/App.tsx
import { Link } from '@tanstack/solid-router'
import { Component } from 'solid-js'

const App: Component = () => {
  return (
    <>
      <div class="p-2 flex gap-2 text-lg">
        <Link
          to="/"
          activeProps={{
            className: 'font-bold',
          }}
          activeOptions={{ exact: true }}
        >
          Home
        </Link>{' '}
        <Link
          to="/posts"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Posts
        </Link>
      </div>

      <hr />
      {/* <Outlet /> */}
      {/* Start rendering router matches */}
      {/* <TanStackRouterDevtools position="bottom-right" /> */}
    </>
  )
}

export default App

// examples/angular/basic/src/app/app.ts
import { Component } from '@angular/core';
import { Link, Outlet, RouterDevtools } from '@tanstack/angular-router';

@Component({
  selector: 'app-root',
  imports: [Outlet, Link, RouterDevtools],
  template: `
    <div className="p-2 flex gap-2 text-lg border-b">
      <a [link]="{ to: '/' }" [linkActive]="{ exact: false }">
        Home
      </a>
      <a link="/posts" linkActive='font-bold'>
        Posts
      </a>
      <a link to="/route-a" linkActive='font-bold'>
        Pathless Layout
      </a>
      <a link="/this-route-does-not-exist" linkActive="font-bold">>
        This Route Does Not Exist
      </a>
    </div>
    <outlet />
    <router-devtools position="bottom-right" />
  `
})
export class AppComponent {}
